dataset: visdrone
weights: runs/train/yolov7-w6-custom-0220-visdrone-4gpu-64w-64b-15epochs-sync-bn/weights/epoch_014.pt
cfg: ''
data: data/visdrone_all.yaml
hyp: data/hyp.scratch.custom.yaml
epochs: 15
batch_size: 64
img_size:
- 1280
- 1280
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: 4,5,6,7
multi_scale: false
single_cls: false
adam: false
sync_bn: true
local_rank: -1
workers: 64
project: runs/train
entity: null
name: yolov7-w6-custom-0220-visdrone-4gpu-64w-64b-15epochs-sync-bn
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 4
global_rank: -1
save_dir: runs/train/yolov7-w6-custom-0220-visdrone-4gpu-64w-64b-15epochs-sync-bn
total_batch_size: 64
